name: RA

on:
  schedule:
    # 04:00 UTC = 05:00 по польскому времени (зимнее время)
    # Запуск каждого 3-го числа месяца
    - cron: '0 4 */3 * *'
  
  workflow_dispatch:
    # Кнопка для ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5  # Обновлено до v5 (поддержка Node 24)

      - name: Set up Python
        uses: actions/setup-python@v6 # Обновлено до v6 (поддержка Node 24)
        with:
          python-version: '3.11'

      # НОВЫЙ ШАГ: Создаем файл из секрета
      - name: Decode Google Credentials
        run: echo "${{ secrets.G_KEYS_BASE64 }}" | base64 --decode > credentials.json

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright gspread oauth2client pandas
          playwright install chromium --with-deps

      - name: Run Python script
        run: python ra.py
        env:
          # Указываем Python, где искать файл с ключами
          GOOGLE_APPLICATION_CREDENTIALS: credentials.json
